# Extra autostart processes
# exec-once = uwsm-app -- my-service

windowrule {
  name = zen-placement
  match:class = zen
  workspace = 1
}

windowrule {
  name = ghostty-placement
  match:class = com.mitchellh.ghostty
  workspace = 3
}

windowrule {
  name = slack-placement
  match:class = slack
  workspace = 5
}

exec-once = /home/carter/.local/share/zen
exec-once = ghostty
exec-once = slack --enable-features=UseOzonePlatform --ozone-platform=wayland
